- name: remove load from loadbalancer
  hosts: "{{ active_host }}"
  vars:
    # active_host: db1.lab.example.com
  tasks:
    - haproxy:
        state: disabled
        host: '{{ inventory_hostname }}'
        # host: db1.lab.example.com
        socket: /var/lib/haproxy/stats
        backend: mariadb_galera
        wait: yes
#        drain: yes
        wait_interval: 1
        wait_retries: 60
#        shutdown_sessions: true
      delegate_to: "{{ item }}"
      with_items: "{{ groups.haproxy }}"
