# vim: set ft=yaml et ts=2 sw=2:
---
- name: deploy HAProxy
  vars:
    proxyhost: haproxy2.lab.example.com
  hosts: "{{ proxyhost }}"
  remote_user: devops
  become: True
  roles:
    - yumupdate
    - haproxysetup
